// Images
export const FETCH_IMAGES = 'FETCH_IMAGES'
export const FETCH_IMAGES_SUCCEEDED = 'FETCH_IMAGES_SUCCEEDED'
export const FETCH_IMAGES_FAILED = 'FETCH_IMAGES_FAILED'
export const FETCH_IMAGE = 'FETCH_IMAGE'
export const FETCH_IMAGE_SUCCEEDED = 'FETCH_IMAGE_SUCCEEDED'
export const FETCH_IMAGE_FAILED = 'FETCH_IMAGE_FAILED'
export const STARTED_WATCHING_IMAGES = 'STARTED_WATCHING_IMAGES'
export const STOPPED_WATCHING_IMAGES = 'STOPPED_WATCHING_IMAGES'
